# permissions for end users to edit capversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capversion-editor-role
rules:
- apiGroups:
  - shipcaps.redradrat.xyz
  resources:
  - capversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shipcaps.redradrat.xyz
  resources:
  - capversions/status
  verbs:
  - get
