apiVersion: shipcaps.redradrat.xyz/v1beta1
kind: Cap
metadata:
  name: namespaces
spec:
  inputs:
    - key: nsname
      type: string
      targetId: namespacename
  values:
    - value: "teststring"
      targetId: teststring
  source:
    type: simple
    inline:
      - apiVersion: v1
        kind: Namespace
        metadata:
          name: "{{ teststring }}"
      - apiVersion: v1
        kind: Namespace
        metadata:
          name: "{{ namespacename }}-test-{{namespacename}}"

